In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
float_data = pd. Series([1.2, -3.5, np.nan, None,1])
print(float_data)
print(float_data.isna())

0    1.2
1   -3.5
2    NaN
3    NaN
4    1.0
dtype: float64
0    False
1    False
2     True
3     True
4    False
dtype: bool


In [3]:
data = pd.Series([1,np.nan, 3.5, np.nan, 7])
data.dropna() # dropping nan- value

0    1.0
2    3.5
4    7.0
dtype: float64

In [4]:
data = pd.DataFrame([[1, 6.5, 3, np.nan], [1, np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan, np.nan]])
data

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN

In [5]:
data.dropna()

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [6]:
data.dropna(how='all')

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN

In [8]:
data.dropna(axis ='columns', how ='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN

In [9]:
data.fillna(0)

0    1    2    3
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [10]:
data.fillna(method ='ffill')

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  6.5  3.0 NaN
2  1.0  6.5  3.0 NaN

In [11]:
data.fillna({1:0,3:2})


0    1    2    3
0  1.0  6.5  3.0  2.0
1  1.0  0.0  NaN  2.0
2  NaN  0.0  NaN  2.0

In [12]:
data = pd.DataFrame({'k1':['one','two']*3 +['two'], 'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [13]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [14]:
data.drop_duplicates(subset=['k1'])

k1  k2
0  one   1
1  two   1

In [15]:
pd.value_counts(data['k2'])

1    2
3    2
4    2
2    1
Name: k2, dtype: int64

In [16]:
result = dict()
for i in data['k2']:
    if(i in result):
        result[i]+=1
    else:
        result[i]=1
pd.Series(result)

1    2
2    1
3    2
4    2
dtype: int64

In [20]:
data = pd.DataFrame({"food": ["tofu", "panner", "vegge"], "ounces": [4, 3, 12]})
data

food  ounces
0    tofu       4
1  panner       3
2   vegge      12

In [22]:
veg_to_vegan ={'tofu': 'soya', 'panner':'dairy', 'vegge':'veg'}
data['vegan'] = data["food"].map(veg_to_vegan)

def get_vegan(x):
    return veg_to_vegan[x]

data['food'].map(get_vegan)

0     soya
1    dairy
2      veg
Name: food, dtype: object

In [23]:
data = pd.Series([1,-999, 2, -999, -1000, 3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [24]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [25]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [26]:
ages=[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [27]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [28]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [29]:
df = pd.DataFrame(np.arange(5*7).reshape(5,7))

df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [30]:
row_sampler = np.random.permutation(5)
print(row_sampler)
df.take(row_sampler)

[1 2 3 0 4]


0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [31]:
col_sampler = np.random.permutation(7)
print(col_sampler)
df.take(col_sampler, axis="columns")

[0 2 4 1 3 5 6]


0   2   4   1   3   5   6
0   0   2   4   1   3   5   6
1   7   9  11   8  10  12  13
2  14  16  18  15  17  19  20
3  21  23  25  22  24  26  27
4  28  30  32  29  31  33  34

In [32]:
import re
pattern = r"[a-zA-Z0-9._%+-]+@[A-Za-z0-9]+\.[A-Za-z]{2,4}"
text="""Dave dave@google.com
Steve steve@gmail.com
Rob rob@googlemail.com
Ryan ryan@yahoo.com"""
regex = re.compile(pattern)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@googlemail.com', 'ryan@yahoo.com']

In [33]:
import re
pattern = r"[a-zA-Z0-9._%+-]+@[A-Za-z0-9]+\.[A-Za-z]{2,4}"
text="""Dave dave@google.com
Steve steve@gmail.com
Rob rob@googlemail.com
Ryan ryan@yahoo.com"""
regex = re.compile(pattern)
regex.split(text)

['Dave ', '\nSteve ', '\nRob ', '\nRyan ', '']